# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(0, 20+1, (4,7))
arr

array([[ 8, 17, 14, 15, 16, 16, 10],
       [12,  3,  0,  3,  5, 11,  5],
       [ 8,  3,  4, 12, 18, 15,  9],
       [16,  5, 16,  5, 13,  5,  2]])

In [ ]:
arr/20

array([[0.4 , 0.85, 0.7 , 0.75, 0.8 , 0.8 , 0.5 ],
       [0.6 , 0.15, 0.  , 0.15, 0.25, 0.55, 0.25],
       [0.4 , 0.15, 0.2 , 0.6 , 0.9 , 0.75, 0.45],
       [0.8 , 0.25, 0.8 , 0.25, 0.65, 0.25, 0.1 ]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
matrix = np.random.randint(0,10+1,(8,10))
print(matrix)
res=[i.sum() for i in matrix]
print(f'Строка: {matrix[res.index(min(res))]}, индекс: {res.index(min(res))}, минимальная сумма: {min(res)}')

[[ 1  5  0  5  4  9  1 10  5  3]
 [ 6  6  8  0  1  4  1  6  4  9]
 [ 9  2  5 10 10  1  5  6  3  9]
 [ 8  7  6  1  1  2  4  3 10  7]
 [ 2  3  7  0  1  0  5  1  6  0]
 [ 0  3  0  7  5  9  1  5  5  7]
 [ 5  5  0  1  3  0  5  1  8  7]
 [10  2 10 10  4  7  6  2  2  0]]
Строка: [2 3 7 0 1 0 5 1 6 0], индекс: 4, минимальная сумма: 25


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
a = np.random.randint(1, 6, 4)
b = np.random.randint(1, 6, 4)
evkl = np.linalg.norm(a - b)
print(a, b, evkl, end = ' ')

# np.linalg.norm() - функция для нахождения евклидова расстояния

[1 2 2 3] [5 1 4 5] 5.0 

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
A = np.array([[-1,2,4], [-3,1,2], [-3,0,1]])
B = np.array([[3,-1], [2,1]])
C = np.array([[7,21], [11,8], [8,4]])
X = np.linalg.inv(A) @ (-C) @ np.linalg.inv(B)
X

array([[ 1.00000000e+00,  5.32907052e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.


    1. loadtxt(fname, dtype=float, comments='#',delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, quotechar=None,like=None)
    2. fname (обязательный) - имя файла или файлоподобный объект, из которого нужно загрузить данные.
    3. dtype (опциональный) - тип данных, в который нужно преобразовать загруженные значения.
    4. comments (опциональный) - символ комментария, все строки, начинающиеся с этого символа, будут проигнорированы.
    5. delimiter (опциональный) - разделитель между значениями в файле.
    6. skiprows (опциональный) - количество строк, которые нужно пропустить перед началом загрузки данных.
    7. usecols (опциональный) - индексы столбцов, которые нужно загрузить.
    8. unpack (опциональный) - если True, данные будут распакованы в отдельные массивы столбцов.
    9. ndmin (опциональный) - минимальное количество измерений, которое должны иметь загруженные данные.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
recipes = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
recipes[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
print(f'Среднее значение для минут =  {np.average(recipes[:,1])}')
print(f'Минимальное значение для минут =  {np.min(recipes[:,1])}')
print(f'Максимальное значение для минут = {np.max(recipes[:,1])}')
print(f'Медиана для минут = {np.median(recipes[:,1])}')

Среднее значение для минут =  21601.00169
Минимальное значение для минут =  0
Максимальное значение для минут = 2147483647
Медиана для минут = 40.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

 np.clip(a, a_min, a_max) - ограничение значений массива в определенном диапазоне

    1. a (обязательный) - массив, значения которого нужно ограничить.
    2. a_min (обязательный) - минимальное значение, которое может принимать массив. Если элемент массива меньше a_min, он будет заменен на a_min.
    3. a_max (обязательный) - максимальное значение, которое может принимать массив. Если элемент массива больше a_max, он будет заменен на a_max.

 np.quantile(a, q, axis=None)

    1. a (обязательный) - массив, для которого нужно вычислить квантиль.
    2. q (обязательный) - значение квантиля, которое должно быть в диапазоне от 0 до 1. Например, 0.5 соответствует медиане.
    3. axis (необязательный) - ось, по которой нужно вычислить квантиль. Если не указано, квантиль вычисляется по всему массиву.

In [ ]:
minutes = recipes[:,1:2]
print("было\n", minutes)
stop = np.clip(minutes, 0, np.quantile(minutes, 0.75))
print("стало\n", stop)
print("ограничение", max(stop))

было
 [[ 60]
 [ 25]
 [ 10]
 ...
 [ 65]
 [  5]
 [140]]
стало
 [[60.]
 [25.]
 [10.]
 ...
 [65.]
 [ 5.]
 [65.]]
ограничение [65.]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
print(len(recipes[:,1:2][recipes[:,1:2] == 0]))
recipes[:,1:2][recipes[:,1:2] == 0] = 1
print(len(recipes[:,1:2][recipes[:,1:2] == 0]))

479
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

 np.unique(arr, axis=None)
1. arr - многомерный массив
2. axis - указывает, по какой оси нужно искать уникальные значения (в случае двумерного массива (матрицы), ось 0 соответствует строкам, а ось 1 соответствует столбцам)

In [ ]:
len(np.unique(recipes, axis=0))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
len(np.unique(recipes[:,2])), np.unique(recipes[:,2])

(37,
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 37, 39], dtype=int32))

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
recipes_5 = recipes[recipes[:,2] <= 5]
print(recipes_5)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
res = np.array([])
for i in range(recipes.shape[0]):
    res = np.append(res, recipes[:,2][i]/recipes[:,1:2][i])
res, res.max()

(array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
        0.1       ]),
 24.0)

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
top100 = np.argsort(recipes[:,1:2])[:100:-1] # индексы рецептов с наибольшей продолжительностью
ingr = np.array([])
for i in top100:
    ingr = np.append(ingr, recipes[:,2][i])
np.average(ingr)

16.0

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
random_recipes = np.random.randint(0, recipes.shape[0], 10)
print(recipes[random_recipes])

[[ 81859      5      6]
 [367704     20      6]
 [285773     35      9]
 [225770     60      9]
 [217653     55     13]
 [ 21667     25      9]
 [514034     60     13]
 [407060     30      7]
 [448258    200     13]
 [312767     30      4]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
aver_ing = np.average(recipes[:,2])
no_more_aver = recipes[:,2][recipes[:,2] < aver_ing]
len(no_more_aver)/len(recipes)*100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
simple_rec2 = np.array((recipes[:, 1] <= 20) & (recipes[:, 2] <= 5)).reshape(-1,1).astype('int')
new_recipes2 = np.concatenate((recipes, simple_rec2), axis=1)
new_recipes2

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

In [ ]:
# arr.reshape(-1,1) - столбец
# arr.reshape(1,-1) - строка

13. Выведите процент "простых" рецептов в датасете

In [ ]:
(simple_rec2[simple_rec2 == 1].shape[0] / simple_rec2.shape[0]) * 100

9.552